language: "python"
python:
    - "3.5"
cache: "pip"
script:
    - py.test
deploy:
    provider: "script"
    script: "deployment/deploy.sh"
    on:
        branch: "master"
        python: "3.5"
        repo: "cerny-jan/zpatkydoma"
