sudo: false
language: "python"
python:
    - "3.5"
cache: "pip"
env:
  -DJANGO_SETTINGS_MODULE=patkydoma.settings.production DJANGO_SECRET_KEY=secretkey DATABASE_URL=postgres://postgres@localhost/test_zpatkydoma GOOGLE_PROJECT_ID=test EMAIL_HOST_USER=test@test.com EMAIL_HOST_PASSWORD=pswd
services:
  - postgresql
before_script:
  - psql -c 'create database test_zpatkydoma;' -U postgres
script: python manage.py test
branches:
  only:
  - master
deploy:
    provider: "script"
    script: "deployment/deploy.sh"
    on:
        branch: "master"
        python: "3.5"
        repo: "cerny-jan/zpatkydoma"
