language: "python"
python:
    - "3.5"
cache: "pip"
services:
  - postgresql
before_script:
  - psql -c 'create database test_zpatkydoma;' -U postgres
script: python manage.py test
branches:
  only:
  - master
deploy:
    provider: "script"
    script: "deployment/deploy.sh"
    on:
        branch: "master"
        python: "3.5"
        repo: "cerny-jan/zpatkydoma"
