language: python
python:
    - 3.5
cache: pip
before_install:
  - chmod +x deployment/deploy.sh
install:
  - pip install -r requirements.txt
services:
  - postgresql
script:
  - python manage.py test
branches:
  only:
  - master
after_success:
  - deployment/deploy.sh
notifications:
  email: false
